server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tanzu_db?useSSL=false&serverTimezone=UTC
    #    username: tomatoo
    #    password: linyugang1356190
    username: root
    password: 123456
cos:
  baseUrl: imge-1319580658.cos.ap-guangzhou.myqcloud.com
  SecretId: AKIDALFIKE4vegkilppdMAsSq0wiIlL0qeUI
  SecretKey: z4A92rdLxRuAD8oLfkprFRRHvLXXItTu
  regionName: ap-guangzhou
  bucketName: imge-1319580658
  folderPrefix: /avg_imge